

CREATE TABLE "audit_application" (
  "application_id" integer PRIMARY KEY,
  "application_name" varchar,
  "application_desc" varchar,
  "status" varchar,
  "created_date" date,
  "created_by" varchar
);

CREATE TABLE "audit_app_task" (
  "application_id" integer,
  "task_id" integer,
  "task_name" varchar,
  "task_desc" varchar,
  "status" varchar,
  "created_date" date,
  "created_by" varchar,
  PRIMARY KEY ("application_id", "task_id")
);

CREATE TABLE "audit_batch_log" (
  "batch_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "application_id" integer,
  "batch_start_time" timestamp,
  "batch_end_time" timestamp,
  "status" varchar,
  "created_date" date,
  "created_by" varchar,
  "last_upd_time" timestamp,
  "last_upd_by" varchar,
  PRIMARY KEY ("batch_id", "application_id")
);

CREATE TABLE "audit_batch_control" (
  "batch_id" integer,
  "application_id" integer,
  "task_id" integer,
  "task_start_time" timestamp,
  "task_end_time" timestamp,
  "status" varchar,
  "source_record_count" integer,
  "target_record_count" integer,
  "created_time" timestamp,
  "created_by" varchar,
  PRIMARY KEY ("batch_id", "application_id", "task_id")
);

ALTER TABLE "audit_app_task" ADD FOREIGN KEY ("application_id") REFERENCES "audit_application" ("application_id");

ALTER TABLE "audit_batch_log" ADD FOREIGN KEY ("application_id") REFERENCES "audit_application" ("application_id");

ALTER TABLE "audit_batch_control" ADD FOREIGN KEY ("batch_id", "application_id") REFERENCES "audit_batch_log" ("batch_id", "application_id");

ALTER TABLE "audit_batch_control" ADD FOREIGN KEY ("application_id", "task_id") REFERENCES "audit_app_task" ("application_id", "task_id");

INSERT INTO audit_application VALUES (101, 'SAMPLE_ETL', 'sample etl process', 'A', current_date, current_user);

INSERT INTO audit_app_task VALUES (101, 1, 'initialize batch', 'start of SAMPLE ETL', 'A', current_date, current_user);
INSERT INTO audit_app_task VALUES (101, 2, 'proc_data_pull', 'collect data for SAMPLE ETL', 'A', current_date, current_user);
INSERT INTO audit_app_task VALUES (101, 3, 'proc_build_dim_1', 'build DIM 1 for SAMPLE ETL', 'A', current_date, current_user);
INSERT INTO audit_app_task VALUES (101, 4, 'proc_build_dim_2', 'build DIM 2 for SAMPLE ETL', 'A', current_date, current_user);
INSERT INTO audit_app_task VALUES (101, 5, 'proc_build_fact_1', 'build FACT 1 for SAMPLE ETL', 'A', current_date, current_user);

SELECT * FROM audit_application;

SELECT * FROM audit_app_task;
